cc_test(
  name = "stl_test",
  srcs = [
    'stl_test.cc'
  ],
)

cc_test(
  name = "string",
  srcs = [
    'string.cc'
  ],
)

cc_test(
  name = "gc_map",
  srcs = [
    'gc_map.cc'
  ],
)

cc_test(
  name = "json",
  srcs = [
    'json.cc'
  ],
  deps = [
    '//thirdparty/jsoncpp:jsoncpp',
    '//toft/base/string:string',
  ],
)

cc_test(
  name = "toft_test",
  srcs = [
    'toft_test.cc'
  ],
  deps = [
    '//toft/system/threading:threading'
  ],
)

cc_test(
  name = "memory_pool",
  srcs = [
    'memory_pool.cc'
  ],
)

cc_test(
  name = "sizeof",
  srcs = [
    'sizeof.cc'
  ],
)

cc_test(
  name = "stl_performance",
  srcs = [
    'stl_performance.cc'
  ],
)

cc_binary(
  name = "nth_element",
  srcs = [
    'nth_element.cc'
  ],
)

cc_binary(
  name = "heap_sort",
  srcs = [
    'heap_sort.cc'
  ],
)

cc_binary(
  name = "binary_tree",
  srcs = [
    'binary_tree.cc'
  ],
)

cc_binary(
  name = "load_material",
  srcs = [
    'load_material.cc'
  ],
  deps = [
    '//toft/base/string:string',
    '//toft/storage/recordio:recordio',
    '//src/proto/:my_message',
  ],
)

cc_binary(
  name = "algorit_1",
  srcs = [
    'algorit_1.cc'
  ],
)

cc_binary(
  name = "c11_features",
  srcs = [
    'c11_features.cc'
  ],
)

cc_binary(
  name = "fcntl",
  srcs = [
    'fcntl.cc'
  ],
)

cc_test(
  name = "std_move_test",
  srcs = [
    'std_move_test.cc'
  ],
)

cc_test(
  name = "emplace_test",
  srcs = [
    'emplace_test.cc'
  ],
)
