cc_test(
  name = "stl_test",
  srcs = [
    'stl_test.cc'
  ],
)

cc_test(
  name = "string",
  srcs = [
    'string.cc'
  ],
)

cc_test(
  name = "gc_map",
  srcs = [
    'gc_map.cc'
  ],
)

cc_test(
  name = "json",
  srcs = [
    'json.cc'
  ],
  deps = [
    '//thirdparty/jsoncpp:jsoncpp',
    '//toft/base/string:string',
  ],
)

cc_test(
  name = "toft_test",
  srcs = [
    'toft_test.cc'
  ],
)

cc_test(
  name = "memory_pool",
  srcs = [
    'memory_pool.cc'
  ],
)

cc_test(
  name = "sizeof",
  srcs = [
    'sizeof.cc'
  ],
)

cc_test(
  name = "stl_performance",
  srcs = [
    'stl_performance.cc'
  ],
)

cc_binary(
  name = "nth_element",
  srcs = [
    'nth_element.cc'
  ],
)
